version: "3.1"

services:
  face-recognizer:
    image: face-recognizer
    build: .
    ports:
      - 8000:8000
    env_file: 
        ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - './../data:/data/db'
    env_file: 
        ./.env
    
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: 
        ./.env
    depends_on:
      - mongo
